from .base_tokens_dep_to_qdmr_extractor import BaseTokensDependenciesToQDMRExtractor
from .spans_based_tokens_dep_to_qdmr_extractor import SpansBasedTokensDependenciesToQDMRExtractor
from .converters import *
