# cwd: ???

# model_name: 'google/t5-v1_1-xl'
model_name: "EleutherAI/gpt-neo-2.7B"
# model_name: "EleutherAI/gpt-neo-125M"
engine: "ada"
output_file: ???
batch_size: 5
# length_file: ???
prompt_file: ???
max_length: 2048
task_name: ???

dataset_reader:
  _target_: src.dataset_readers.few_shot_dsr.FewShotDatasetReader
  model_name: ${model_name}
  task_name: ${task_name} 
    # _target_: src.dataset_readers.tasks.break_task.BreakTask
  prompt_file: ${prompt_file}
  # length_file: ${length_file}
