cuda_device: ???
output_file: ???
setup_type: ???
dataset_split: ???
task_name: ???
batch_size: 50
model_name: 'sentence-transformers/paraphrase-mpnet-base-v2'
dataset_reader:
  _target_: src.dataset_readers.indexer_dsr.IndexerDatasetReader
  task_name: ${task_name}
  setup_type: ${setup_type}
  dataset_split: ${dataset_split}
  model_name: ${model_name}
model:
  _target_: src.models.embedder.IndexEmbedder
  model_name: ${model_name}
