batch_size: 1
model_name: "EleutherAI/gpt-neo-2.7B"
# model_name: "EleutherAI/gpt-neo-125M"
output_file: ???
example_file: ???
setup_type: ???
task_name: ???

dataset_reader:
  _target_: src.dataset_readers.scorer_dsr.ScorerDatasetReader
  example_file: ${example_file}
  task_name: ${task_name} 
  model_name: ${model_name}
  setup_type: ${setup_type}
model:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: ${model_name}

